apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ykv8fijnb-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ykv8fijnb-java-quarkus-gitops